#  Copyright (C) 2010-2017, OpenUp S.A. , http://www.openup.com.uy
#  Copyright (C) 2003-2017, e-Evolution Consultants S.A. , http://www.e-evolution.com
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#  Email: raul.capecce@openupsolutions.com, http://openupsolutions.com , http://github.com/rcapecce
#  Email: victor.perez@e-evolution.com, http://www.e-evolution.com , http://github.com/e-Evolution
#

version: '3'
services:
  db:
    image: postgres:9.6
    restart: always
    container_name: ADEMPIERE_DB_PG_96
    volumes:
      - data:/var/lib/postgresql/data/
    ports:
      - "${ADEMPIERE_DB_PORT}:5432"
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
      - PGDATA:/var/lib/postgresql/data/pgdata
      - POSTGRES_DB:adempiere
      - POSTGRES_INITDB_ARGS:''
      - POSTGRES_INITDB_XLOGDIR:''

  adempiere-tenant:
    depends_on:
      - db
    image: ${ADEMPIERE_TENANT}
    container_name: ${ADEMPIERE_TENANT}
    ports:
      - ${ADEMPIERE_WEB_PORT}:8888
      - ${ADEMPIERE_SSL_PORT}:444
    environment:
      ADEMPIERE_DB_INIT: ${ADEMPIERE_DB_INIT}
    build:
      context: .
      dockerfile: ./adempiere-last/Dockerfile
      args:
        ADEMPIERE_REL: ${ADEMPIERE_VERSION}
        ADEMPIERE_SRC_DIR: "./${ADEMPIERE_TENANT}"
        ADEMPIERE_DB_HOST: ${ADEMPIERE_DB_SERVER}
        ADEMPIERE_DB_PORT: ${ADEMPIERE_DB_PORT}
        ADEMPIERE_DB_NAME: ${ADEMPIERE_TENANT}
        ADEMPIERE_DB_USER: ${ADEMPIERE_DB_USER}
        ADEMPIERE_DB_PASSWORD: ${ADEMPIERE_DB_PASSWORD}
        ADEMPIERE_DB_ADMIN_PASSWORD: ${ADEMPIERE_DB_ADMIN_PASSWORD}

  #adempiere-tenant2:
  #  depends_on:
  #    - db
  #  image: adempiere-tenant2
  #  container_name: adempiere-tenant2
  #  ports:
  #    - 8274:8888
  #  environment:
  #    ADEMPIERE_DB_INIT: Y
  #  build:
  #    context: .
  #    dockerfile: ./adempiere-last/Dockerfile
  #    args:
  #      ADEMPIERE_REL: 390LTS
  #      ADEMPIERE_SRC_DIR: ./tenant2
  #      ADEMPIERE_DB_HOST: 10.10.1.122
  #      ADEMPIERE_DB_PORT: 54321
  #      ADEMPIERE_DB_NAME: dbtenant2
  #      ADEMPIERE_DB_USER: usertenant2
  #      ADEMPIERE_DB_PASSWORD: postgres
  #      ADEMPIERE_DB_ADMIN_PASSWORD: postgres

volumes:
  data: {}
