version: '3'
services:
  db:
    image: postgres:9.6
    restart: always
    volumes:
      - data:/var/lib/postgresql/data/
    command: postgres -c config_file=/postgresql/postgresql.conf  
    ports:
      - "54321:5432"  
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
      - PGDATA:/var/lib/postgresql/data/pgdata
      - POSTGRES_DB:adempiere
      - POSTGRES_INITDB_ARGS:''
      - POSTGRES_INITDB_XLOGDIR:''
volumes:
  data: {}      
      
