version: '2'


services:

  adpg:
    image: adpg:9.6
    build:
      context: .
      dockerfile: ./postgres/Dockerfile

  adpg-client1:
    depends_on:
      - adpg
    image: adpg-client1
    container_name: adpgc-client1
    network_mode: host
    volumes:
      - /tmp/mnt:/var/lib/postgresql/9.6/main/
    build:
      context: ./postgres-db
      dockerfile: ./Dockerfile
      args:
        PG_Port: 5432
        PG_DBName: adempiere_db
        PG_AdempierePsw: adempierepsw
        PG_PGAdminPsw: postgrespsw
        PG_MaxConnections: 1000
        PG_Net: 192.168.1.0
        PG_NetMask: 24


